"use client";

import { FormEvent, useState } from "react";

const whatsappNumber = "5548999163731";
const whatsapp = "(48) 99916-3731";
const whatsappHref = `https://wa.me/${whatsappNumber}?text=${encodeURIComponent("Olá, Carla! Gostaria de conversar sobre o acompanhamento para meu filho.")}`;
function Arrow() { return <span aria-hidden="true">→</span>; }
function LeafMark() { return <span className="leaf-mark" aria-hidden="true"><i /><i /><i /></span>; }
function WhatsAppIcon() { return <svg className="whatsapp-icon" viewBox="0 0 32 32" aria-hidden="true" focusable="false"><path fill="currentColor" d="M16 2a13.92 13.92 0 0 0-11.94 21.09L2 30l7.12-1.87A14 14 0 1 0 16 2Zm0 25.5a11.48 11.48 0 0 1-5.85-1.6l-.42-.25-4.23 1.11 1.13-4.12-.27-.43A11.5 11.5 0 1 1 16 27.5Zm6.3-8.62c-.35-.18-2.08-1.03-2.4-1.15-.32-.12-.55-.18-.79.18-.23.35-.9 1.15-1.1 1.39-.2.23-.4.26-.75.09a9.34 9.34 0 0 1-2.76-1.7 10.32 10.32 0 0 1-1.91-2.38c-.2-.35 0-.54.16-.71.16-.16.35-.4.52-.6.18-.2.24-.35.35-.59.12-.23.06-.44-.03-.61-.09-.18-.79-1.91-1.08-2.62-.29-.69-.58-.6-.79-.61h-.67c-.23 0-.61.09-.93.44-.32.35-1.22 1.19-1.22 2.9s1.25 3.37 1.42 3.6c.18.24 2.46 3.76 5.96 5.27.83.36 1.48.57 1.99.73.84.27 1.61.23 2.22.14.68-.1 2.08-.85 2.37-1.67.29-.82.29-1.53.2-1.67-.08-.14-.31-.23-.67-.41Z" /></svg>; }
function CarlaPortrait({ alt, priority = false }: { alt: string; priority?: boolean }) {
  return <picture className="portrait-picture">
    <source type="image/webp" srcSet="/carla-prado-profissional-640.webp 640w, /carla-prado-profissional-1122.webp 1122w" sizes="(max-width: 820px) 88vw, 42vw" />
    <img className="portrait-image" src="/carla-prado-profissional-1122.jpg" srcSet="/carla-prado-profissional-640.jpg 640w, /carla-prado-profissional-1122.jpg 1122w" sizes="(max-width: 820px) 88vw, 42vw" width={1122} height={1402} alt={alt} loading={priority ? "eager" : "lazy"} fetchPriority={priority ? "high" : "auto"} decoding="async" />
  </picture>;
}

function CarlaAboutPortrait() {
  return <picture className="portrait-picture">
    <source type="image/webp" srcSet="/carla-prado-retrato-natural-640.webp 640w, /carla-prado-retrato-natural-951.webp 951w" sizes="(max-width: 820px) 100vw, 42vw" />
    <img className="portrait-image" src="/carla-prado-retrato-natural-951.jpg" srcSet="/carla-prado-retrato-natural-640.jpg 640w, /carla-prado-retrato-natural-951.jpg 951w" sizes="(max-width: 820px) 100vw, 42vw" width={951} height={1189} alt="Retrato profissional de Carla Prado" loading="lazy" decoding="async" />
  </picture>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [formNotice, setFormNotice] = useState("");
  function submitForm(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const message = [
      "Olá, Carla! Gostaria de conversar sobre o acompanhamento para meu filho.",
      `Nome do responsável: ${data.get("responsavel") ?? ""}`,
      `Idade da criança: ${data.get("idade") ?? ""}`,
      `Principal dificuldade: ${data.get("dificuldade") ?? ""}`,
      `WhatsApp para retorno: ${data.get("whatsapp") ?? ""}`,
    ].join("\n");
    window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer");
    setFormNotice("Abrindo uma conversa no WhatsApp com Carla.");
  }
  return <main>
    <header className="site-header">
      <a href="#inicio" className="brand" aria-label="Carla Prado, início"><LeafMark /><span>Carla <strong>Prado</strong></span></a>
      <button className="menu-button" type="button" aria-expanded={menuOpen} aria-controls="main-menu" onClick={() => setMenuOpen(!menuOpen)}><span /><span /><span /><span className="sr-only">Abrir menu</span></button>
      <nav id="main-menu" className={menuOpen ? "open" : ""} aria-label="Navegação principal">
        <a href="#sobre" onClick={() => setMenuOpen(false)}>Sobre Carla</a><a href="#acompanhamento" onClick={() => setMenuOpen(false)}>Acompanhamento</a><a href="#para-quem" onClick={() => setMenuOpen(false)}>Para quem é</a><a href="#faq" onClick={() => setMenuOpen(false)}>Dúvidas</a><a href="#contato" className="nav-contact" onClick={() => setMenuOpen(false)}>Conversar</a>
      </nav>
    </header>

    <section className="hero" id="inicio">
      <div className="hero-copy"><p className="eyebrow"><LeafMark /> Desenvolvimento &amp; aprendizagem infantil</p><h1>Cada criança aprende e se desenvolve de um jeito. <em>Entender esse caminho faz diferença.</em></h1><p className="hero-text">Acompanhamento individualizado para crianças de 6 a 13 anos com desafios no desenvolvimento e na aprendizagem, conectando as necessidades da criança à realidade da família e da escola.</p><div className="hero-actions"><a className="button button-primary" href={whatsappHref} target="_blank" rel="noreferrer">Conversar com Carla <Arrow /></a><a className="text-link" href="#acompanhamento">Conhecer o trabalho <Arrow /></a></div><div className="credential"><span className="credential-line" /><p><strong>Carla Prado</strong><br />Pedagoga <b>•</b> Especialista em Neuropsicopedagogia <b>•</b> Formação em ABA</p></div></div>
      <div className="hero-portrait"><CarlaPortrait priority alt="Carla Prado, pedagoga e especialista em desenvolvimento e aprendizagem infantil" /><p className="portrait-caption">Atendimento em<br /><strong>Criciúma — SC</strong></p></div>
    </section>

    <section className="section problems" id="para-quem"><div className="section-intro narrow"><p className="eyebrow">Um olhar para o cotidiano</p><h2>Quando procurar acompanhamento?</h2><p>Nem sempre a preocupação começa com um nome técnico. Muitas vezes, ela aparece nas pequenas situações da rotina, em casa ou na escola.</p></div><div className="problem-grid">{["Meu filho está tendo dificuldade para acompanhar a escola.","Ele sabe fazer, mas parece não conseguir manter a atenção.","A leitura e a escrita não estão avançando como esperávamos.","A escola relata dificuldades frequentes de participação ou comportamento.","Ele precisa de muita ajuda para realizar atividades que já poderiam ser mais autônomas.","Recebemos um diagnóstico e não sabemos como transformar as orientações em ações práticas."].map((item) => <article className="problem-card" key={item}><span className="quote">“</span><p>{item}</p></article>)}</div><p className="context-note">Essas situações podem estar relacionadas a diferentes condições — como TEA, TDAH, transtornos de aprendizagem e alterações do desenvolvimento —, mas o ponto de partida é sempre compreender a criança e o que ela vive.</p></section>

    <section className="section connection" id="acompanhamento"><div className="section-intro"><p className="eyebrow">O diferencial do acompanhamento</p><h2>A criança não existe separada da família e da escola.</h2><p>Compreender uma dificuldade envolve observar mais do que uma habilidade isolada. É considerar como a criança aprende, se comunica, participa e constrói autonomia nos diferentes contextos da sua rotina.</p></div><div className="connection-layout"><div className="connection-orbit" aria-label="Conexão entre criança, família e escola"><span className="orbit orbit-one" /><span className="orbit orbit-two" /><div className="orbit-node family"><span aria-hidden="true" style={{ color: "var(--terracotta)", fontSize: "1.35rem", lineHeight: 1, marginBottom: "9px" }}>⌂</span><strong>Família</strong></div><div className="orbit-node school"><span aria-hidden="true" style={{ color: "var(--terracotta)", fontSize: "1.15rem", lineHeight: 1, marginBottom: "10px" }}>▤</span><strong>Escola</strong></div><div className="orbit-center"><LeafMark /><strong>Criança</strong><span>necessidades<br />e objetivos</span></div></div><div className="pillar-list"><article><span>01</span><div><h3>Criança</h3><p>Compreender habilidades, dificuldades, necessidades e objetivos individuais.</p></div></article><article><span>02</span><div><h3>Família</h3><p>Transformar orientações em estratégias possíveis dentro da rotina.</p></div></article><article><span>03</span><div><h3>Escola</h3><p>Considerar as demandas reais de aprendizagem, participação e desenvolvimento.</p></div></article></div></div></section>

    <section className="section services"><div className="section-intro"><p className="eyebrow">Possibilidades de acompanhamento</p><h2>Um trabalho voltado à criança e à família.</h2><p>Atendimento individual para crianças de 6 a 13 anos. Cada encontro dura 50 minutos; a frequência é definida de acordo com as necessidades de cada caso e pode ser semanal.</p></div><div className="service-grid"><article><span className="service-number">01</span><h3>Acompanhamento individual infantil</h3><p>Acompanhamento planejado de acordo com as necessidades de desenvolvimento e aprendizagem da criança.</p></article><article><span className="service-number">02</span><h3>Acompanhamento neuropsicopedagógico</h3><p>Estratégias de acompanhamento relacionadas ao desenvolvimento e à aprendizagem, dentro dos limites técnicos e éticos da atuação profissional.</p></article><article><span className="service-number">03</span><h3>Orientação à família</h3><p>Estratégias para ajudar responsáveis a compreender e lidar com situações da rotina, aprendizagem e desenvolvimento.</p></article><article><span className="service-number">04</span><h3>Integração com o contexto escolar</h3><p>Quando necessária e autorizada pela família, consideração de informações relevantes para dar coerência ao acompanhamento.</p></article></div><div className="topic-links" aria-label="Acompanhamentos por necessidade"><a className="topic-link-card" href="/autismo-criciuma"><span>Autismo (TEA)</span><h3>Acompanhamento pedagógico para crianças autistas</h3><p>Estratégias individualizadas para aprendizagem, autonomia, rotina e participação escolar.</p><b>Conhecer o acompanhamento →</b></a><a className="topic-link-card" href="/deficiencia-intelectual-criciuma"><span>Deficiência intelectual</span><h3>Apoio pedagógico individualizado</h3><p>Um trabalho voltado à aprendizagem, autonomia e participação no contexto escolar.</p><b>Conhecer o acompanhamento →</b></a></div></section>

    <section className="about" id="sobre"><div className="about-image"><CarlaAboutPortrait /></div><div className="about-copy"><p className="eyebrow">Sobre Carla Prado</p><h2>Conhecimento técnico com presença na realidade da criança.</h2><p>Carla Prado é pedagoga, especialista em Neuropsicopedagogia e possui formação complementar em ABA. Sua experiência no ambiente escolar e no atendimento individual contribui para um olhar atento às demandas que atravessam a vida da criança.</p><p>Na pós-graduação, aprofundou estudos em desenvolvimento humano, psicologia do desenvolvimento e da aprendizagem, desenvolvimento psicomotor, neurofisiologia, neurociência e teoria e prática da Neuropsicopedagogia.</p><p>A experiência dentro da escola e no acompanhamento individual permite considerar não apenas uma dificuldade específica, mas também como a criança aprende, participa e responde às demandas presentes em sua rotina.</p><div className="formation"><p><strong>Formação certificada</strong><br />Pedagogia — <i>FAPI – Faculdade Pinhais, concluída em 2013</i><br />Pós-graduação lato sensu em Neuropsicopedagogia — <i>Centro Universitário Leonardo da Vinci (UNIASSELVI), 440 horas, concluída em 2015</i><br />Formação ABA PRO — <i>NeuroConecta, 120 horas, concluída em 2025</i></p><p><strong>Ênfase da formação em ABA</strong><br /><i>Princípios da ABA, técnicas de ensino, análise funcional, habilidades de comunicação, participação familiar e contexto escolar.</i></p></div><div className="experience"><p><strong>Experiência profissional</strong></p><ul><li><b>2021–2023</b> — Professora temporária de Atendimento Educacional Especializado (AEE).</li><li><b>2024</b> — Professora temporária em atendimento residencial, na rede pública estadual de Santa Catarina, com estudantes com TEA.</li><li><b>2025</b> — Segunda professora temporária na rede pública estadual de Santa Catarina, acompanhando estudantes com TEA, TDAH e outras necessidades educacionais.</li></ul></div></div></section>

    <section className="section journey"><div className="section-intro narrow"><p className="eyebrow">Como funciona</p><h2>Um caminho construído com clareza.</h2><p>O acompanhamento é pensado de forma individualizada e começa por uma conversa sobre o momento que a criança e a família estão vivendo.</p></div><ol className="journey-list"><li><span>01</span><div><h3>Conversa inicial</h3><p>Compreensão da principal preocupação da família e do contexto atual da criança.</p></div></li><li><span>02</span><div><h3>Conhecimento da criança e da rotina</h3><p>Levantamento das necessidades relacionadas ao desenvolvimento e à aprendizagem.</p></div></li><li><span>03</span><div><h3>Planejamento individualizado</h3><p>Definição de objetivos e estratégias adequados às necessidades identificadas.</p></div></li><li><span>04</span><div><h3>Acompanhamento</h3><p>Trabalho individual e acompanhamento dos objetivos estabelecidos.</p></div></li><li><span>05</span><div><h3>Família e contexto escolar</h3><p>Quando pertinente e autorizado, integração de informações para favorecer coerência na rotina.</p></div></li></ol></section>

    <section className="section faq" id="faq"><div className="section-intro narrow"><p className="eyebrow">Perguntas frequentes</p><h2>Algumas dúvidas que podem surgir.</h2></div><div className="faq-list">{[["Para quais crianças o acompanhamento pode ser indicado?","Para crianças de 6 a 13 anos que apresentam desafios relacionados ao desenvolvimento, à aprendizagem, à atenção, à autonomia, à participação escolar ou à rotina. A conversa inicial ajuda a entender se este é o caminho mais adequado."],["Meu filho precisa ter diagnóstico?","Não. Muitas famílias procuram acompanhamento a partir de uma dificuldade percebida no dia a dia. Quando há diagnóstico, ele pode ajudar a compreender o contexto, mas não substitui o olhar para as necessidades individuais da criança."],["Como funciona o primeiro contato?","A família conta, de forma breve, o que está vivendo. A partir dessa conversa, Carla poderá orientar sobre a possibilidade de acompanhamento e os próximos passos."],["Quanto dura o encontro e qual é a frequência?","Cada encontro dura 50 minutos. A frequência é definida conforme as necessidades de cada criança e pode ser semanal."],["A família participa?","Sim. A participação da família é importante para que orientações e estratégias façam sentido na rotina real da criança."],["A escola pode contribuir com informações?","Quando for pertinente e autorizado pela família, informações do contexto escolar podem contribuir para compreender melhor as demandas da criança."],["Como funcionam pagamento, cancelamento e remarcação?","O pagamento pode ser realizado por Pix ou dinheiro. O valor do atendimento é informado diretamente pelo WhatsApp. Cancelamentos ou pedidos de remarcação comunicados com pelo menos 24 horas de antecedência não geram cobrança."],["Onde acontece o atendimento?","O atendimento acontece em espaço próprio, no bairro Mina do Mato, em Criciúma — SC. O endereço é informado após o contato inicial e o agendamento."]].map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>

    <section className="contact" id="contato"><div className="contact-copy"><p className="eyebrow"><LeafMark /> Contato inicial</p><h2>Quer entender se esse acompanhamento faz sentido para seu filho?</h2><p>Conte um pouco sobre o momento que vocês estão vivendo. A partir dessa conversa inicial, será possível compreender melhor a necessidade da criança e os próximos passos.</p><div className="contact-location"><span>⌖</span><p><strong>Atendimento em espaço próprio, no bairro Mina do Mato, em Criciúma — SC</strong><br />Segunda a sexta, das 8h às 12h e das 13h30 às 18h</p></div></div><form className="contact-form" onSubmit={submitForm}><label>Nome do responsável<input required name="responsavel" placeholder="Como podemos chamar você?" /></label><label>Idade da criança<input required name="idade" inputMode="numeric" placeholder="Ex.: 7 anos" /></label><label>Principal dificuldade<textarea required name="dificuldade" rows={3} placeholder="Conte brevemente o que motivou o contato" /></label><label>WhatsApp<input required name="whatsapp" inputMode="tel" placeholder="(48) 9 0000-0000" /></label><button className="button button-primary" type="submit">Conversar com Carla pelo WhatsApp <Arrow /></button>{formNotice && <p className="form-notice" role="status">{formNotice}</p>}<p className="privacy">Ao enviar, você concorda com o <a href="#politica">Aviso de privacidade</a>. Evite compartilhar diagnósticos ou informações clínicas neste primeiro contato.</p></form></section>

    <section className="section privacy-policy" id="politica"><div className="section-intro narrow"><p className="eyebrow">Privacidade</p><details className="privacy-details"><summary>Aviso de privacidade<span>+</span></summary><div className="privacy-copy"><p><strong>Dados coletados.</strong> O formulário solicita o nome do responsável, a idade da criança, uma descrição breve da principal dificuldade e um número de WhatsApp para retorno.</p><p><strong>Finalidade.</strong> Esses dados são usados exclusivamente para compreender o motivo do contato e conversar com a família sobre a possibilidade de acompanhamento. Dados adicionais serão coletados pessoalmente e armazenados somente se houver contratação do serviço.</p><p><strong>WhatsApp.</strong> O formulário não mantém um banco de dados próprio no site: ao ser enviado, ele abre uma conversa com Carla pelo WhatsApp. As mensagens do primeiro contato serão mantidas por até 90 dias, conforme a configuração de mensagens adotada no WhatsApp.</p><p><strong>Cuidados com informações de crianças.</strong> Não envie diagnósticos, laudos ou outras informações clínicas no primeiro contato. A família poderá apresentar informações adicionais pessoalmente, quando necessário e apropriado.</p><p><strong>Direitos e contato.</strong> Para dúvidas, solicitações de acesso ou exclusão relacionadas às informações do contato inicial, escreva para <a href="mailto:carlajplgomes@gmail.com">carlajplgomes@gmail.com</a>.</p></div></details></div></section>

    <footer><a href="#inicio" className="brand"><LeafMark /><span>Carla <strong>Prado</strong></span></a><p>Desenvolvimento e aprendizagem com um olhar que conecta criança, família e escola.</p><div><a href="/autismo-criciuma">Autismo</a><a href="/deficiencia-intelectual-criciuma">Deficiência intelectual</a><a href={whatsappHref} target="_blank" rel="noreferrer">WhatsApp: {whatsapp}</a></div><small>© {new Date().getFullYear()} Carla Prado.</small></footer><a className="whatsapp-float" href={whatsappHref} target="_blank" rel="noreferrer" aria-label="Conversar com Carla pelo WhatsApp"><WhatsAppIcon /><span className="whatsapp-label-short">Conversar</span><span className="whatsapp-label-full">Conversar pelo WhatsApp</span></a>
  </main>;
}
